spring:
  application:
    name: uaa-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
        enabled: true
        server-addr: http://[NACOS-SERVER-ADDR]:8848

server:
  port: 18000
  servlet:
    context-path: /uaa

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.commons.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.uaa: debug

